Repository Garlic-Team/gcommands, pull requests merged in 2021-06, with the labels that each got.

#21 4.1.3
  package.json
  src/base/GCommands.js
  src/base/GCommandsDispatcher.js
  src/base/GEvents.js
  src/base/actions/guildmember.js
  src/index.js
  src/managers/GCommandLoader.js
  src/managers/GDatabaseLoader.js
  src/managers/GEventLoader.js
  src/structures/ButtonEvent.js
  src/structures/DMChannel.js
  src/structures/NewsChannel.js
  src/structures/TextChannel.js
  src/structures/message.js
  src/util/models/user.js
  src/util/updater.js
  src/util/util.js
Labels: new version

#24 Add polish translation to message.json
  src/util/message.json
Labels: enhancement, t: global

#26 version(4.2.7): Bug Fixes, DB change
  .gitignore
  README.md
  package-lock.json
  package.json
  src/base/GCommands.js
  src/base/GCommandsDispatcher.js
  src/base/GEvents.js
  src/base/actions/interactions.js
  src/managers/GCommandLoader.js
  src/managers/GDatabaseLoader.js
  src/managers/GEventLoader.js
  src/structures/ButtonEvent.js
  src/structures/guild.js
  src/structures/message.js
  src/util/Constants.js
  src/util/cmdUtils.js
  src/util/models/guild.js
  src/util/models/user.js
  src/util/util.js
Labels: bug, priority: medium, t: global
