Repository Garlic-Team/gcommands, pull requests merged in 2021-08, with the labels that each got.

#87 Client code pause fix
  src/base/GCommandsClient.js
  src/base/GCommandsDispatcher.js
  src/structures/GGuild.js
Labels: priority: high, type: bugfix

#100 Add Italian language
  src/util/message.json
Labels: type: enhancement, semver: patch

#76 Guide revamp [WIP]
  .github/workflows/vuebuild.yml
  .gitignore
  guide/.vuepress/components/Branch.vue
  guide/.vuepress/components/BranchSelector.vue
  guide/.vuepress/components/DisMessage.vue
  guide/.vuepress/components/Language.vue
  guide/.vuepress/components/LanguageSelector.vue
  guide/.vuepress/components/Notice.vue
  guide/.vuepress/components/V2v3.vue
  guide/.vuepress/config.js
  guide/.vuepress/enhanceApp.js
  guide/.vuepress/mixins/branches.js
  guide/.vuepress/mixins/languages.js
  guide/.vuepress/public/addbot.png
  guide/.vuepress/public/contextmenu.png
  guide/.vuepress/public/createapp.png
  guide/.vuepress/public/oauth2.png
  guide/.vuepress/public/selectmenu.png
  guide/.vuepress/public/token.png
  guide/.vuepress/styles/index.styl
  guide/README.md
  guide/guide/README.md
  guide/guide/additional/fromv2tov3.md
  guide/guide/additional/fromv3tov4.md
  guide/guide/additional/fromv4tov5.md
  guide/guide/additional/fromv5tov6.md
  guide/guide/arguments/usingargsincmd.md
  guide/guide/beginner/additionalfeatures.md
  guide/guide/beginner/basicbot.md
  guide/guide/beginner/database.md
  guide/guide/beginner/events.md
  guide/guide/faq.md
  guide/guide/interactions/contextmenus.md
  guide/guide/interactions/messagecomponents.md
  guide/guide/interactions/slashcommands.md
  guide/guide/miscellaneous/inhibitor.md
  guide/guide/miscellaneous/interactions.md
  guide/guide/miscellaneous/mentions.md
  guide/guide/miscellaneous/moreevents.md
  guide/guide/setup.md
  package-lock.json
  package.json
Labels: meta: documentation, type: enhancement, s: approved

#131 Adding french in message.json
  src/util/message.json
Labels: type: enhancement, semver: minor, s: awaiting review

#145 feat(Command): CommandBuilders
  src/index.js
  src/structures/CommandArgBuilder.js
  src/structures/CommandArgChoiceBuilder.js
  src/structures/CommandBuilder.js
  typings/index.d.ts
Labels: type: enhancement, semver: minor, s: approved

#146 Added typings for ArgumentType
  typings/index.d.ts
Labels: semver: patch, s: approved

#148 fix(Argument): argument returns choice value
  src/commands/argument.js
Labels: priority: high, type: bugfix, semver: patch, s: approved

#152 feat(Argument): SUB_COMMAND and SUB_COMMAND_GROUP 🎉
  src/commands/argument.js
  src/commands/types/sub_command.js
  src/commands/types/sub_command_group.js
  src/managers/GCommandLoader.js
  src/managers/GEventHandling.js
  src/structures/BaseCommandInteraction.js
  src/util/Constants.js
  src/util/message.json
  typings/index.d.ts
Labels: type: enhancement, semver: major, s: approved
