Repository Garlic-Team/gcommands, pull requests merged in 2021-07, with the labels that each got.

#27 4.2.8
  package.json
  src/base/GCommandsDispatcher.js
  src/base/actions/interactions.js
  src/index.js
  src/managers/GEventLoader.js
  src/structures/DMChannel.js
  src/structures/InteractionEvent.js
  src/structures/MessageActionRow.js
  src/structures/MessageButton.js
  src/structures/MessageSelectMenu.js
  src/structures/MessageSelectMenuOption.js
  src/structures/NewsChannel.js
  src/structures/TextChannel.js
  src/structures/guild.js
  src/structures/message.js
  src/structures/v12/SelectMenuCollector.js
  src/structures/v13/SelectMenuCollector.js
Labels: documentation, enhancement, new version, priority: medium, t: global

#29 4.3.0
  .github/workflows/docs.yml
  .github/workflows/vuebuild.yml
  README.md
  package-lock.json
  package.json
  src/base/GCommands.js
  src/base/GEvents.js
  src/base/actions/guildmember.js
  src/index.js
  src/managers/GCommandLoader.js
  src/managers/GDatabaseLoader.js
  src/managers/GEventLoader.js
  src/structures/DMChannel.js
  src/structures/GGuild.js
  src/structures/GMessage.js
  src/structures/InteractionEvent.js
  src/structures/MessageActionRow.js
  src/structures/MessageButton.js
  src/structures/MessageSelectMenu.js
  src/structures/NewsChannel.js
  src/structures/TextChannel.js
  src/structures/guild.js
  src/structures/message.js
  src/util/Constants.js
  src/util/util.js
  tsconfig.json
  typings/index.d.ts
  typings/index.ts
Labels: documentation, enhancement, priority: high, t: global

#53 feat(Color): More Colors
  FUNDING.yml
  src/structures/Color.js
Labels: type: enhancement
