Repository Garlic-Team/gcommands, pull requests merged in 2021-09, with the labels that each got.

#157 fix(JSDoc): Fixed examples and added parameters for Client events.
  src/util/Constants.js
Labels: meta: documentation, s: awaiting review

#160 Fix GCommandLoader.js __loadCommandFiles to support filenames with multiple dots
  src/managers/GCommandLoader.js
Labels: type: bugfix, semver: patch, s: awaiting review

#159 fix(GPayload): allowedMentions
  src/structures/GPayload.js
Labels: type: bugfix, semver: patch, s: awaiting review

#161 Fix(typings): EventOptionsBuilder & Command
  typings/index.d.ts
Labels: type: bugfix, semver: patch, s: approved

#166 Fixes for 'Edit this page' 🔨
  guide/.vuepress/config.js
Labels: meta: documentation, semver: patch, s: approved

#168 `README` update 🧄
  README.md
Labels: s: approved

#167 fix(context & slash): fix for context and slash command options
  src/managers/GCommandLoader.js
  src/managers/GEventHandling.js
  src/structures/CommandArgsOptionBuilder.js
  src/util/Constants.js
  typings/index.d.ts
Labels: type: bugfix, semver: major, s: awaiting review

#128 chore(7.0.0): 🐢
  .github/workflows/dev-docs.yml
  .github/workflows/docs.yml
  .github/workflows/labeler.yml
  .github/workflows/rebase.yml
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  src/base/GCommands.js
  src/base/GCommandsClient.js
  src/base/GCommandsDispatcher.js
  src/commands/argument.js
  src/commands/base.js
  src/commands/types/base.js
  src/commands/types/integer.js
  src/commands/types/number.js
  src/commands/types/string.js
  src/commands/types/sub_command.js
  src/commands/types/sub_command_group.js
  src/index.js
  src/managers/GCommandLoader.js
  src/managers/GDatabaseLoader.js
  src/managers/GEventHandling.js
  src/structures/CommandArgsChoiceBuilder.js
  src/structures/CommandArgsOptionBuilder.js
  src/structures/CommandInteraction.js
  src/structures/CommandOptionsBuilder.js
  src/structures/Event.js
  src/structures/EventOptionsBuilder.js
  src/structures/GError.js
  src/structures/GGuild.js
  src/structures/GInteraction.js
  src/structures/GMessage.js
  src/structures/GPayload.js
  src/structures/MessageActionRow.js
  src/structures/MessageButton.js
  src/structures/MessageComponentInteraction.js
  src/structures/MessageSelectMenu.js
  src/structures/MessageSelectMenuOption.js
  src/structures/TextChannelBase.js
  src/structures/v12/ButtonCollector.js
  src/structures/v12/InteractionCollector.js
  src/structures/v12/SelectMenuCollector.js
  src/structures/v13/ButtonCollector.js
  src/structures/v13/InteractionCollector.js
  src/structures/v13/SelectMenuCollector.js
  src/util/Constants.js
  src/util/message.json
  src/util/util.js
  typings/index.d.ts
Labels: type: enhancement, priority: high, semver: major, s: awaiting review

#176 Fix GMessage and Arguments
  src/commands/base.js
  src/managers/GEventHandling.js
  src/structures/CommandOptionsBuilder.js
  src/structures/GMessage.js
  typings/index.d.ts
Labels: type: bugfix, semver: patch, s: approved

#177 7.0.1
  package.json
  src/commands/base.js
  src/managers/GEventHandling.js
  src/structures/CommandOptionsBuilder.js
  src/structures/GMessage.js
  typings/index.d.ts
Labels: semver: patch, s: approved

#180 guide(alwaysObtain): explanation for alwaysObtain
  guide/.vuepress/config.js
  guide/guide/other/alwaysobtain.md
Labels: meta: documentation, s: approved

#184 fix(slash permissions & error.response.status) + feat(loadFromCache)
  src/base/GCommandsClient.js
  src/managers/GCommandLoader.js
  src/util/Constants.js
  typings/index.d.ts
Labels: priority: high, type: bugfix, semver: patch, s: awaiting review

#185 Change to using path for fileName and fileType in GCommandLoader, fix directory scanning
  src/managers/GCommandLoader.js
Labels: s: awaiting review

#189 feat(followUp): add followUp() for slash and message commands
  src/managers/GEventHandling.js
  src/structures/GInteraction.js
  src/util/Constants.js
  typings/index.d.ts
Labels: type: enhancement, semver: minor

#187 fix(Arguments): Arguments return correct value
  src/commands/argument.js
  src/commands/types/base.js
  src/commands/types/boolean.js
  src/commands/types/channel.js
  src/commands/types/integer.js
  src/commands/types/mentionable.js
  src/commands/types/number.js
  src/commands/types/role.js
  src/commands/types/string.js
  src/commands/types/sub_command.js
  src/commands/types/sub_command_group.js
  src/commands/types/user.js
  src/managers/GEventHandling.js
Labels: type: bugfix, semver: patch, s: approved

#203 feat(Arguments): cancel (button)
  src/commands/argument.js
  src/commands/types/boolean.js
  src/managers/GEventHandling.js
  src/util/Constants.js
Labels: s: awaiting review
