Repository Garlic-Team/gcommands, pull requests merged in 2022-05, with the labels that each got.

#439 fix: regexp for command validation
  src/lib/util/regexes.ts
Labels: semver: patch

#438 chore(SECURITY): add security policy
  .github/SECURITY.md
Labels: chore

#437 feat: add options option to structures
  src/lib/structures/Command.ts
  src/lib/structures/Component.ts
  src/lib/structures/Listener.ts
  src/lib/structures/Plugin.ts
Labels: semver: minor

#457 feat: Add support for modals, and fix some other stuff
  src/handlers/AutocompleteHandler.ts
  src/handlers/ComponentHandler.ts
  src/handlers/InteractionCommandHandler.ts
  src/handlers/MessageCommandHandler.ts
  src/lib/managers/HandlerManager.ts
  src/lib/structures/Component.ts
  src/lib/structures/contexts/AutocompleteContext.ts
  src/lib/structures/contexts/CommandContext.ts
  src/lib/structures/contexts/ComponentContext.ts
  src/lib/structures/contexts/Context.ts
  src/listeners/ComponentHandler.ts
Labels: semver: minor, discord.js changes, api changes

#459 fix: types CacheType should not be undefined
  src/lib/structures/contexts/AutocompleteContext.ts
  src/lib/structures/contexts/CommandContext.ts
  src/lib/structures/contexts/ComponentContext.ts
  src/lib/structures/contexts/Context.ts
Labels: semver: patch, typings

#413 docs: improve jsdocs
  .eslintrc.json
  src/index.ts
  src/lib/GClient.ts
  src/lib/loaders/directoryLoader.ts
  src/lib/loaders/pluginFinder.ts
  src/lib/util/Util.ts
Labels: documentation

#463 chore: documentation workflow
  .github/workflows/documentation.yml
  .npmignore
  docs/docs.yml
  scripts/docs.mjs
Labels: chore
