Repository Garlic-Team/gcommands, pull requests merged in 2022-01, with the labels that each got.

#291 fix: Inhibitor docs
  scripts/config.json
  scripts/docs.mjs
  scripts/next-docs.mjs
Labels: semver: patch, documentation

#292 fix: listener unregister
  src/lib/managers/ListenerManager.ts
  src/lib/structures/Listener.ts
Labels: semver: patch

#318 chore: github workflow
  .github/workflows/next-release.yml
  package.json
Labels: in progress, chore

#319 chore: typedoc-plugin-djs-links
  .github/workflows/docs.yml
  .github/workflows/next-docs.yml
  package-lock.json
  package.json
Labels: chore, documentation
