Repository Garlic-Team/gcommands, pull requests merged in 2022-04, with the labels that each got.

#391 feat(Command, Argument): localizations
  src/lib/structures/Argument.ts
  src/lib/structures/Command.ts
  src/lib/util/common.ts
Labels: semver: minor

#411 fix: command & option name regex validating
  src/lib/structures/Argument.ts
  src/lib/structures/Command.ts
  src/lib/util/regexes.ts
Labels: semver: patch

#415 fix: add {duration} variable
  src/handlers/ComponentHandler.ts
  src/handlers/InteractionCommandHandler.ts
  src/handlers/MessageCommandHandler.ts
Labels: semver: patch

#420 fix: Argument choice value should allow numbers
  src/lib/structures/Argument.ts
Labels: semver: patch

#419 feat: support for dynamic prefix & multiple prefixes
  src/lib/GClient.ts
  src/listeners/MessageCommandHandler.ts
Labels: semver: minor

#432 feat: support for command permissions v2
  src/handlers/MessageCommandHandler.ts
  src/lib/structures/Command.ts
  src/lib/structures/Component.ts
  src/lib/structures/contexts/CommandContext.ts
  src/lib/util/Util.ts
Labels: semver: minor, api changes
